server:  
  port: 8080
  
spring:  
   datasource:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8&useSSL=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat
      useGlobalDataSourceStat: true 
mybatis: 
   mapperLocations: classpath:mapper/*.xml
   typeAliasesPackage: com.mountain.po

  
